name: ai_hshm
description: "An AI Application"

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  appwrite: ^13.0.0



  cupertino_icons: ^1.0.8
  lottie: ^3.1.3


  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  hive: ^4.0.0-dev.2

  get: ^4.6.6

  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.2

  http: ^1.2.2

  dart_openai: ^5.1.0
  cached_network_image: ^3.4.1

  translator_plus: ^1.0.1

  gallery_saver_updated: ^3.0.0

  share_plus: ^10.1.2

  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
